# ----------------------------------------
# CONFIGURAÇÕES GERAIS DO PROJETO
# ----------------------------------------
spring.application.name=meudinheiro
gemini.api.key=${GEMINI_API_KEY}
logging.level.web=TRACE

# ----------------------------------------
# FIREBASE AUTENTICAÇÃO
# ----------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/meu-dinheiro-app-b75e2

# ----------------------------------------
# BANCO DE DADOS POSTGRESQL (RAILWAY)
# ----------------------------------------
# Substitua as linhas antigas por estas:
spring.datasource.url=jdbc:postgresql://mainline.proxy.rlwy.net:48850/railway
spring.datasource.username=postgres
spring.datasource.password=MFOMzPAYiQnVezXCVaKJvsyliwFZeZah
spring.datasource.driverClassName=org.postgresql.Driver

# ----------------------------------------
# CONFIGURAÇÕES DO HIBERNATE (JPA)
# ----------------------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurações do WhatsApp Meta API
whatsapp.api.phone-id=1057225407476161
whatsapp.api.token=EAAXAtJfxB88BRNlPRfFa3wFkjk7KZB6rXiZClAE00RZCBo7ujIZAnbzLaDWVaLq1ZBKyJidZBZBuQ97pJpIhN4u7tvodMm11jTnKAmDJ28lvs717x73kgEfsfRXr0tqh7Ope1sKZCfvssfaZBdAq55REOZCyH5VosJuJqYFyyLENZAEA0KHlVhAQD7y4YakViiZCfwtLmDRmVhzNhoBrwDEfdBZBZAxWOMrNlJ3iAu5qlW2TP3iGjZARv2aCPn8mWFRJjVEBPNBjxnSDaB1cAtVj5mXiQQHBgZDZD

#Define o perfil local como padrão ao rodar no PC
#spring.profiles.active=dev