spring.application.name=meudinheiro

# Configuração do Banco de Dados H2 (Memória)
spring.datasource.url=jdbc:h2:mem:expensedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite que o Hibernate crie as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=create

# Habilita o console do H2 no navegador (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

gemini.api.key=AIzaSyDPPEAFQxEfa-UK-s12UN-JY_DXcHQSr6M
logging.level.web=TRACE